import { MovieScene } from "./types";

export const PRESET_SCENES: MovieScene[] = [
  {
    id: "medusa-awakening",
    title: "Medusa's Temple",
    tagline: "Mythological Epic",
    description: "Medusa standing in a green smoky stone cavern. Her snake hair starts writhing and hissing as she slowly lifts her glowing sword.",
    presetPrompt: "Cinematic medium shot of Medusa in a foggy ancient Greek temple, green ambient vapor. Her snake hair writhes and hisses realistically, her glowing eyes shine with magical energy, and she raises a glittering silver sword as dust particles float in the air. 8k, photorealistic, slow dramatic camera rotation, cinematic lighting.",
    aspectRatio: "16:9",
    colorTheme: "from-emerald-950 via-teal-900 to-zinc-950",
    imageThumbnail: "🐍",
    badge: "Most Popular",
  },
  {
    id: "forest-friends",
    title: "Cartoon Expedition",
    tagline: "Adventure & Animation",
    description: "A group of cute, expressive cartoon animals (fox, bunny, bear) walking cheerfully down a lush mountain forest pathway.",
    presetPrompt: "Expressive 3D Disney-style animation of a cute orange fox, a fluffy bunny, and a friendly brown bear walking happily down a lush forest trail. Sunbeams filtering through large green trees, vibrant wildflowers. The characters smile, waving at the camera. Slow cinematic pan forward, warm golden-hour lighting.",
    aspectRatio: "16:9",
    colorTheme: "from-amber-950 via-orange-900 to-stone-950",
    imageThumbnail: "🦊",
    badge: "Trending",
  },
  {
    id: "forest-leviathan",
    title: "The Forest Giant",
    tagline: "Fantasy & Mystery",
    description: "A colossal, friendly light-blue creature with glowing antenna watching knight horse-riders navigate through misty woods.",
    presetPrompt: "A giant, gentle blue creature with wide curious eyes and glowing antennas looms over a misty, magical pine forest. Three horse riders on white stallions look up in awe. Thick glowing fog swirls around the fern-covered ground. Slow upward crane shot, majestic fantasy atmosphere, ethereal sunrise.",
    aspectRatio: "16:9",
    colorTheme: "from-cyan-950 via-blue-900 to-slate-950",
    imageThumbnail: "🦕",
    badge: "Atmospheric",
  },
  {
    id: "heavenly-deer",
    title: "Sky Sanctuary",
    tagline: "Ethereal Dreamscape",
    description: "A majestic deer with blooming flower antlers, surrounded by owls and mushroom spirits floating on cloud islands.",
    presetPrompt: "Ethereal cinematic sequence of a beautiful deer with blooming pink and white roses growing on its antlers. Cute round owls and mushroom spirits hover on floating fluffy clouds. Bright soft pink and golden dawn light, feathers and sparkles drifting gently. Smooth slow motion drift, dreamy anime style.",
    aspectRatio: "16:9",
    colorTheme: "from-rose-950 via-pink-900 to-indigo-950",
    imageThumbnail: "🦌",
    badge: "Dreamy",
  },
  {
    id: "cosmic-nebula",
    title: "Cosmic Odyssey",
    tagline: "Sci-Fi Visuals",
    description: "A mesmerizing fly-through of an interstellar nebula filled with gas clouds, glowing planets, and stardust.",
    presetPrompt: "A hyper-detailed fly-through of a colorful cosmic nebula. Swirling waves of deep blue, violet, and orange stellar gases. Glistening rings of planetary systems and brilliant star clusters sparkling in the vacuum. Slow-motion cosmic dolly zoom, deep-space cinema.",
    aspectRatio: "16:9",
    colorTheme: "from-indigo-950 via-purple-900 to-black",
    imageThumbnail: "🌌",
    badge: "Sci-Fi",
  },
  {
    id: "jewel-princess",
    title: "Diamond Royalty",
    tagline: "Fashion & Glamour",
    description: "A high-fashion portrait of a graceful woman wearing intricate diamond and blue sapphire necklaces and earrings.",
    presetPrompt: "Glamorous high-end fashion close-up of a royal princess adorned with intricate diamond and sapphire choker jewelry. Studio lighting reflecting brilliant sparkles off the gemstones. The camera slowly pivots around her elegant profile as she opens her eyes with a soft look. Ultra premium quality, pristine lighting.",
    aspectRatio: "9:16",
    colorTheme: "from-slate-950 via-sky-950 to-zinc-950",
    imageThumbnail: "💎",
    badge: "Glamour",
  },
];
